import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const data=new Map();
const ctx=vm.createContext({S:{get:(k,d)=>structuredClone(data.get(k)??d)}});
vm.runInContext(source.slice(source.indexOf('function toBase('),source.indexOf('function whLogUse(')),ctx);
const {toBase,fromBase,addQuantity,whFormat,whTotal,whAddPackages,wfFifoUse,whProducts}=ctx;
const plain=x=>JSON.parse(JSON.stringify(x));
assert.deepEqual(plain(toBase('2,5','KG')),{qty:2500,unit:'g'});
assert.equal(fromBase(toBase(500,'g'),'kg'),.5);
assert.equal(fromBase(toBase(2,'L'),'ml'),2000);
assert.equal(addQuantity({qty:2,unit:'kg'},{qty:500,unit:'g'}).qty,2.5);
assert.equal(addQuantity({qty:1,unit:'L'},{qty:250,unit:'ml'}).qty,1.25);
for(const units of [['g','ml'],['kg','L'],['conf','g'],['conf','ml']])assert.throws(()=>addQuantity({qty:1,unit:units[0]},{qty:1,unit:units[1]}),/incompatibili/);
for(const qty of [-1,NaN,Infinity,'abc'])assert.throws(()=>toBase(qty,'g'));
assert.throws(()=>toBase(1,'g/m²'));
for(const [label,qty,unit] of [['Sacco 25 kg',25000,'g'],['Flacone 0,5 L',500,'ml'],['500g',500,'g']]){
  const f=whFormat({label});assert.deepEqual(plain(toBase(f.size,f.unit)),{qty,unit});
}
for(const label of ['Confezione','2 x 500 g','Sacco 25 kg + 500 g','Sacco 25'])assert.equal(whFormat({label}).unit,'conf');
const bag=(id,qty,unit,date)=>({id,original_qty:qty,remaining_qty:qty,unit,added_date:date});
const p={id:'solid',unit:'kg',packages:[bag('old',2,'kg','2026-01-01')]};
const stocks=whAddPackages([p],{id:'solid',unit:'g',packages:[bag('new',500,'g','2026-02-01')]});
assert.equal(whTotal(stocks[0]),2.5);
assert.equal(stocks[0].unit,'kg');assert.equal(stocks[0].packages[1].remaining_qty,500);
const used=wfFifoUse(stocks,'solid',2200,'g');
assert.equal(used.used,2200);assert.equal(whTotal(used.products[0]),.3);
assert.equal(used.products[0].packages[1].remaining_qty,300);
assert.equal(whTotal(stocks[0]),2.5,'FIFO non muta lo stato in ingresso');
assert.throws(()=>wfFifoUse(stocks,'solid',1,'L'),/incompatibili/);
assert.throws(()=>whAddPackages(stocks,{id:'solid',unit:'conf',packages:[bag('unknown',1,'conf','2026-03-01')]}),/incompatibili/);
const legacy={id:'legacy',unit:'kg',packages:[{id:'a',remaining_qty:2,format:'2 kg'},{id:'b',remaining_qty:500,format:'500 g'}]};
assert.equal(whTotal(legacy),2.5,'riconosce l’unità del formato legacy senza riscrittura');
const oldConf={id:'padana',unit:'conf',format:'Sacco 25 kg',packages:[{id:'c',remaining_qty:1,format:'Sacco 25 kg'}]};
assert.equal(whTotal(oldConf),1);
assert.throws(()=>wfFifoUse([oldConf],'padana',1,'kg'),/incompatibili/);
data.set('dss_warehouse_v2',[{id:'flat',u:'kg',qty:2,ini:3},oldConf,legacy]);
const saved=JSON.stringify([...data]);
assert.equal(whTotal(whProducts()[0]),2);assert.equal(whProducts()[0].unit,'kg');
assert.equal(JSON.stringify([...data]),saved,'lettura legacy senza migrazione in storage');
assert.ok(Number.isNaN(whTotal({unit:'kg',packages:[bag('bad',1,'L','')]})),'giacenza incompatibile segnalata come non confrontabile');
console.log('OK: conversioni, formati, somme incompatibili, FIFO, lettura prudente legacy');
